app.config(['$routeProvider',function($routeProvider){
	$routeProvider.when('/:page?',{
		controller:'mainController',
		templateUrl:'app/partials/home.html'
	}).
	when('/search/:term/:page?',{
		controller:'searchController',
		templateUrl:'app/partials/search.html'
	}).
	when('/book/:BookId',{
		controller:'BookController',
		templateUrl:'app/partials/book_view.html'
	}).
	otherwise({'redirectTo':'/'});
}]);